---
title: "[Q#16243580][A#16243661] Mockito How to mock and assert a thrown exception?"
question_title: "Mockito How to mock and assert a thrown exception?"
question_text: "I'm using mockito in a junit test. How do you make an exception happen and then assert that it has (generic pseudo-code)"
answer_text: "Mockito alone is not the best solution for handling exceptions, use Mockito with Catch-Exception"
apization_code: "package com.stackoverflow.api;  /**  * Mockito How to mock and assert a thrown exception?  *  * @author APIzator  * @see <a href=\"https://stackoverflow.com/a/16243661\">https://stackoverflow.com/a/16243661</a>  */ public class APIzator16243661 {    public static void mock() throws RuntimeException {     given(otherServiceMock.bar()).willThrow(new MyException());     when(myService).foo();     then(caughtException()).isInstanceOf(MyException.class);   } }"
---

https://stackoverflow.com/q/16243580

I&#x27;m using mockito in a junit test. How do you make an exception happen and then assert that it has (generic pseudo-code)



## Original code snippet

https://stackoverflow.com/a/16243661

Mockito alone is not the best solution for handling exceptions, use Mockito with Catch-Exception

```java
given(otherServiceMock.bar()).willThrow(new MyException());

when(myService).foo();

then(caughtException()).isInstanceOf(MyException.class);
```

## Produced APIzation

[`APIzator16243661.java`](https://github.com/pasqualesalza/apization-temp-data/raw/master/apizations/java/APIzator16243661.java)

```java
package com.stackoverflow.api;

/**
 * Mockito How to mock and assert a thrown exception?
 *
 * @author APIzator
 * @see <a href="https://stackoverflow.com/a/16243661">https://stackoverflow.com/a/16243661</a>
 */
public class APIzator16243661 {

  public static void mock() throws RuntimeException {
    given(otherServiceMock.bar()).willThrow(new MyException());
    when(myService).foo();
    then(caughtException()).isInstanceOf(MyException.class);
  }
}

```